# Generated by Django 3.1.1 on 2020-10-19 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20201019_1848'),
    ]

    
