# Generated by Django 3.1.1 on 2020-10-19 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20201019_1852'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='authors',
        ),
    ]
