# Generated by Django 3.1.1 on 2020-10-19 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20201019_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='authors',
        ),
    ]
