# Generated by Django 3.1.1 on 2020-10-19 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_remove_post_author_id'),
    ]

  