# Generated by Django 3.1.1 on 2020-10-19 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_post_authors'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='authors',
            field=models.CharField(default='', max_length=100),
        ),
    ]
