# Generated by Django 3.1.2 on 2020-10-17 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='contact_dt',
            new_name='timestamp',
        ),
    ]
